# Data Analysis for 2018 MLB Pitches

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

unproccessedData = pd.read_csv(os.getcwd() + '/../data/pitchData2018.csv', error_bad_lines=False)
cols_1 = unproccessedData.columns.tolist()
print (len(cols_1))
print (cols_1)
unproccessedData.head()

b'Skipping line 38037: expected 89 fields, saw 177\n'

89
['pitch_type', 'game_date', 'release_speed', 'release_pos_x', 'release_pos_z', 'player_name', 'batter', 'pitcher', 'events', 'description', 'spin_dir', 'spin_rate_deprecated', 'break_angle_deprecated', 'break_length_deprecated', 'zone', 'des', 'game_type', 'stand', 'p_throws', 'home_team', 'away_team', 'type', 'hit_location', 'bb_type', 'balls', 'strikes', 'game_year', 'pfx_x', 'pfx_z', 'plate_x', 'plate_z', 'on_3b', 'on_2b', 'on_1b', 'outs_when_up', 'inning', 'inning_topbot', 'hc_x', 'hc_y', 'tfs_deprecated', 'tfs_zulu_deprecated', 'fielder_2', 'umpire', 'sv_id', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'sz_top', 'sz_bot', 'hit_distance_sc', 'launch_speed', 'launch_angle', 'effective_speed', 'release_spin_rate', 'release_extension', 'game_pk', 'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4', 'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8', 'fielder_9', 'release_pos_y', 'estimated_ba_using_speedangle', 'estimated_woba_using_speedangle', 'woba_value', 'woba_denom', 'babip_value', 'iso_value', 'launch_speed_angle', 'at_bat_number', 'pitch_number', 'pitch_name', 'home_score', 'away_score', 'bat_score', 'fld_score', 'post_away_score', 'post_home_score', 'post_bat_score', 'post_fld_score', 'if_fielding_alignment', 'of_fielding_alignment']

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment
0,KC,2018-04-16,82.7,-1.4584,6.0715,Dellin Betances,518618,476454,NaN,ball,...,12,1,1,12,1,12,1,12,Standard,Standard
1,FF,2018-04-16,97.4,-1.1494,6.2583,Dellin Betances,518618,476454,NaN,called_strike,...,12,1,1,12,1,12,1,12,Standard,Standard
2,FF,2018-04-16,97.4,-1.1243,6.2821,Dellin Betances,592407,476454,NaN,called_strike,...,12,1,1,12,1,12,1,12,Standard,Standard
3,FF,2018-04-16,96.8,-1.0854,6.3578,Dellin Betances,543776,476454,NaN,called_strike,...,12,1,1,12,1,12,1,12,Standard,Standard
4,FF,2018-04-16,96.2,-1.1785,6.1612,Dellin Betances,543776,476454,NaN,called_strike,...,12,1,1,12,1,12,1,12,Standard,Standard

In [12]:
# Scrub data of rows we dont need
data = unproccessedData.drop(['events','hit_distance_sc','launch_speed','launch_angle','umpire','sv_id','hc_x','hc_y','tfs_deprecated','tfs_zulu_deprecated','hit_location','bb_type','game_year','des','game_type','spin_dir','spin_rate_deprecated','break_angle_deprecated','break_length_deprecated','bat_score','fld_score','fielder_2.1', 'pitcher.1','fielder_2','fielder_3','fielder_4','fielder_5', 'fielder_6', 'fielder_7', 'fielder_8', 'fielder_9','estimated_woba_using_speedangle','estimated_ba_using_speedangle','woba_value','iso_value', 'babip_value','woba_denom','launch_speed_angle','at_bat_number','home_score','away_score','post_away_score','post_home_score','post_bat_score','post_fld_score','if_fielding_alignment','of_fielding_alignment'], axis=1)
cols = data.columns.tolist()
print (len(cols))
cols

363430
42

['pitch_type',
 'game_date',
 'release_speed',
 'release_pos_x',
 'release_pos_z',
 'player_name',
 'batter',
 'pitcher',
 'description',
 'zone',
 'stand',
 'p_throws',
 'home_team',
 'away_team',
 'type',
 'balls',
 'strikes',
 'pfx_x',
 'pfx_z',
 'plate_x',
 'plate_z',
 'on_3b',
 'on_2b',
 'on_1b',
 'outs_when_up',
 'inning',
 'inning_topbot',
 'vx0',
 'vy0',
 'vz0',
 'ax',
 'ay',
 'az',
 'sz_top',
 'sz_bot',
 'effective_speed',
 'release_spin_rate',
 'release_extension',
 'game_pk',
 'release_pos_y',
 'pitch_number',
 'pitch_name']

In [3]:
data.describe()

,release_speed,release_pos_x,release_pos_z,batter,pitcher,zone,balls,strikes,pfx_x,pfx_z,...,ay,az,sz_top,sz_bot,effective_speed,release_spin_rate,release_extension,game_pk,release_pos_y,pitch_number
count,361963.000000,361896.000000,361896.000000,363430.000000,363430.000000,361896.000000,363430.000000,363430.000000,361896.000000,361896.000000,...,361896.000000,361896.000000,362477.000000,362477.000000,361693.000000,356590.000000,361947.000000,363430.000000,361896.000000,363430.000000
mean,88.440532,-0.766888,5.871642,549752.683675,554263.168709,10.571910,0.725367,0.708068,-0.140860,0.646834,...,26.157437,-23.524615,3.428669,1.605111,87.939981,2231.741479,5.981427,530556.320717,54.518238,2.517139
std,6.020521,1.979540,0.519222,71569.335295,73418.288769,3.748365,0.913539,0.798491,0.877797,0.756783,...,3.821456,8.803566,0.213335,0.135359,6.345891,306.848256,0.504990,673.675087,0.504944,1.567919
min,44.200000,-5.004700,1.057700,112526.000000,112526.000000,1.000000,0.000000,0.000000,-2.421500,-2.013400,...,6.647900,-51.235000,2.503800,0.797000,46.279000,428.000000,2.494000,529406.000000,50.609700,1.000000
25%,84.200000,-2.202400,5.608600,500871.000000,502085.000000,8.000000,0.000000,0.000000,-0.902900,0.213100,...,23.301400,-29.640025,3.290400,1.520400,83.586000,2083.000000,5.655000,529970.000000,54.185300,1.000000
50%,89.800000,-1.552200,5.913150,571431.000000,572020.000000,12.000000,0.000000,0.000000,-0.238900,0.819300,...,26.235450,-22.148250,3.427300,1.605700,89.360000,2246.000000,5.990000,530554.000000,54.510000,2.000000
75%,93.100000,1.192400,6.197600,605170.000000,607200.000000,14.000000,1.000000,1.000000,0.579900,1.247100,...,28.943325,-16.216775,3.566600,1.692500,92.779000,2407.000000,6.314000,531140.000000,54.844400,3.000000
max,105.000000,5.333200,7.527100,670950.000000,673633.000000,14.000000,3.000000,2.000000,2.432700,3.838900,...,47.216500,13.552900,4.448400,2.382900,105.298000,3671.000000,9.888000,531727.000000,58.006100,15.000000

In [15]:
len(data[data["type"] == "B"])

247497

In [8]:
len(data[data["type"] == "S"])

115933

In [ ]:
# Use p_throws, stand, plate_x, plate_z as features